# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./...
      
    - name: Run go vet
      run: go vet -v ./...

    - name: Tests
      run: go test ./...
